services:
  dev:
    # Note that the path of the Dockerfile and context is relative to the *primary*
    # docker-compose.yml file (the first in the devcontainer.json "dockerComposeFile"
    # array). The sample below assumes your primary file is in the root of your project.
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile
    shm_size: '32gb'
    env_file:
      - .env
    volumes:
      - .:/workspace/project:cached
      - pip_cache:/root/.cache/pip:cached
      - data:/workspace/data:cached
    command: /bin/sh -c "while sleep 1000; do :; done"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
        limits:
          memory: 55g
volumes:
  data:
  pip_cache:
