name: Customize template
on: create
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Find and Replace
        uses: jacobtomlinson/gha-find-replace@v3
        with:
          find: "<<[repository_name]>>"
          replace: "${{ github.event.repository.name }}"
          regex: false
      - name: Substitute README.md
        run: mv README_TEMPLATE.md README.md
      - name: Push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
permissions:
  actions: write